[build]
  publish = "static"
  command = "curl -fsSL https://bun.sh/install | bash && export PATH=\"$HOME/.bun/bin:$PATH\" && cd static/layers-osrs && bun install && bun start"

[build.environment]
  NODE_VERSION = "20"

[[headers]]
  for = "/layers-osrs/map/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
